version: "3"

services:

  app:
    container_name: ${FLASK_CONTAINER_NAME}
    build: 
      context: app
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    depends_on:
      - db
    environment:
      - DATABASE
      - FLASK_APP
      - FLASK_DEBUG
      - DATABASE_URL
      - APP_FOLDER

    ports:
      - 5000:5000
    
  db:
    container_name: ${PGSQL_CONTAINER_NAME}
    hostname: ${PGSQL_CONTAINER_NAME}
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB

volumes:
  db-data:
    name: flaskproject-pgslq-data
